numpy:
  - 1.26
libprotobuf:
  - 5.28.2
protobuf:
  - 5.28.2
spdlog:
  - 1.14
pugixml:
  - '1.14'

cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.11.* *_cpython
python_impl:
  - cpython

c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win and x86_64]
  - vs2022                     # [win and arm64]
cxx_compiler_version:          # [unix]
  - 13                         # [linux]
  - 18                         # [osx]
  - vs2019                     # [win]
