numpy:
  - 2
assimp:
  - 5
libprotobuf:
  - 6.31.1
protobuf:
  - 6.31.1
spdlog:
  - 1.17
pugixml:
  - '1.15'
libopencv:
  - 4.12.0
libxml2:
  - 2.14.*
graphviz:
  - 14.*
# Mitigation for
# https://github.com/RoboStack/ros-jazzy/pull/126#issuecomment-3515455380
libcap:
  - 2.77
fmt:
  - 12.1
lua:
  - 5.4
tbb:
  - '2022'
tbb_devel:
  - '2022'

# Workaround for https://github.com/RoboStack/ros-jazzy/pull/40#issuecomment-2782226697
cmake:
  - 3.*

cdt_name:  # [linux]
  - conda  # [linux]

python:
  - 3.12.* *_cpython
python_impl:
  - cpython

emscripten_emscripten-wasm32:
  - 3.1.45
cross-python_emscripten-wasm32:
  - 3.11.* *_12

c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
  - vs2022                     # [win]
  - emscripten                 # [emscripten]
c_compiler_version:            # [unix]
  - 14                         # [linux]
  - 18                         # [osx]
c_stdlib:
  - sysroot                    # [linux]
  - macosx_deployment_target   # [osx]
  - vs                         # [win]
c_stdlib_version:              # [unix]
  - 2.17                       # [linux]
  - 10.13                      # [osx and x86_64]
  - 11.0                       # [osx and arm64]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2022                     # [win]
  - emscripten                 # [emscripten]
cxx_compiler_version:          # [unix]
  - 14                         # [linux]
  - 18                         # [osx]

libzenohc:
  - 1.7.2
libzenohcxx:
  - 1.7.2

libhwloc:
  - 2.12.2
