[project]
name = "ros-humble"
# Just a convention, this is the same as the mutex package
version = "0.6.0"
description = "RoboStack repo to package ros-humble packages as conda packages"
authors = ["Tobias Fischer <tobias.fischer@qut.edu.au>", "Wolf Vollprecht <w.vollprecht@gmail.com>", "Silvio Traversaro <silvio@traversaro.it>"]
channels = ["https://repo.prefix.dev/conda-forge"]
platforms = ["osx-arm64", "linux-64", "osx-64", "linux-aarch64", "win-64"]

[system-requirements]
# 2.17 is the glibc version used in centos 7
libc = { family="glibc", version="2.17" }

[tasks]
upload = "anaconda -t $ANACONDA_API_TOKEN upload"

[dependencies]
python = ">=3.11.0,<3.12"
rattler-build = ">=0.34.1"
anaconda-client = ">=1.12"

[target.win-64.dependencies]
# patch is required by rattler-build
m2-patch = "*"
# git is required by rattler-build
git = "*"

[feature.beta.pypi-dependencies]
# This is tipically the latest commit on main branch
vinca = { git = "https://github.com/RoboStack/vinca.git", rev = "aa102b280adcad0374e4d231b25d21bf0db27d61" }
# Uncomment this line to work with a local vinca for faster iteration, but remember to comment it back
# (and regenerate the pixi.lock) once you push the modified commit to the repo
#vinca = { path = "../vinca", editable = true }

[feature.emscripten.pypi-dependencies]
# pull vinca emscripten branch
vinca = { path = "../vinca", editable = true} 
# vinca = { git = "https://github.com/RoboStack/vinca.git", rev = "aa102b280adcad0374e4d231b25d21bf0db27d61" }

[feature.beta.tasks]
generate-recipes = { cmd = "vinca -m", depends-on = ["rename-file"] }
remove-file = { cmd = "rm vinca.yaml; rm -rf recipes" }
copy_additional_recipes = { cmd = "sh -c 'find additional_recipes/* -maxdepth 0 -type d -exec ln -s ../{} recipes/ \\;'" }
build = { cmd = "rattler-build build --recipe-dir ./recipes -m ./conda_build_config.yaml -c robostack-staging -c https://repo.prefix.dev/conda-forge --skip-existing", depends-on = ["generate-recipes", "copy_additional_recipes"] }
build_one_package = { cmd = "cp ./patch/$PACKAGE.*patch ./recipes/$PACKAGE/patch/; rattler-build build --recipe ./recipes/$PACKAGE/recipe.yaml -m ./conda_build_config.yaml -c robostack-staging -c https://repo.prefix.dev/conda-forge", env = { PACKAGE = "ros-humble-ros-workspace" } }
create_snapshot = { cmd = "vinca-snapshot -d humble -o snapshot_$(date +\"%Y-%m-%d-%H-%M-%S\").yaml" }

[environments]
beta = ["beta"]
emscripten = ["emscripten"]

[feature.emscripten.tasks.build]
  cmd = [
      "rattler-build", "build",
      "--package-format", "tar-bz2",
      "--recipe-dir", "./recipes",
      "-m", "./conda_build_config.yaml",
      "-c", "https://repo.prefix.dev/conda-forge",
      # "-c", "file:///Users/fischert/robot/wasm-rattler/emscripten-forge-recipes/output",
      "-c", "file:///Users/fischert/robot/wasm-rattler/emscripten-forge-recipes-old/output",
      "-c", "https://repo.mamba.pm/emscripten-forge",
      # "-c", "https://repo.mamba.pm/robostack-wasm",
      # "-c", "file:///home/nmarticorena/Documents/pixi_project/recipes/output",
      # "-c", "file:///Users/fischert/robot/ros-humble/output",
      "-c", "robostack-staging",
      "--target-platform", "emscripten-wasm32",
      "--skip-existing",
      "--test", "skip"
      ]
  depends-on = ["generate-recipes", "copy_additional_recipes"]

[feature.emscripten.tasks]
# build_additional_recipes = {cmd = "sh -c 'find additional_recipes/* -maxdepth 0 -type d -exec ln -s ../{} recipes/ \\;'"}
generate-recipes = { cmd = "vinca -m --platform emscripten-wasm32", depends-on = ["rename-file"] }
remove-file = { cmd = "rm vinca.yaml; rm -rf recipes" }
copy_additional_recipes = { cmd = "sh -c 'find additional_recipes/* -maxdepth 0 -type d -exec ln -s ../{} recipes/ \\;'" }
build_one_package = { cmd = "cp ./patch/$PACKAGE.*patch ./recipes/$PACKAGE/patch/; rattler-build build --recipe ./recipes/$PACKAGE/recipe.yaml -m ./conda_build_config.yaml -c robostack-staging -c https://repo.prefix.dev/conda-forge", env = { PACKAGE = "ros-humble-ros-workspace" } }
create_snapshot = { cmd = "vinca-snapshot -d humble -o snapshot_$(date +\"%Y-%m-%d-%H-%M-%S\").yaml" }
rename-file = { cmd = "ln -s vinca_emscripten32.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.linux-64.tasks]
rename-file = { cmd = "ln -s vinca_linux_64.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.osx-64.tasks]
rename-file = { cmd = "ln -s vinca_osx.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.osx-arm64.tasks]
rename-file = { cmd = "ln -s vinca_osx_arm64.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.linux-aarch64.tasks]
rename-file = { cmd = "ln -s vinca_linux_aarch64.yaml vinca.yaml", depends-on = ["remove-file"] }

[target.win-64.tasks]
rename-file = { cmd = "cp vinca_win.yaml vinca.yaml", depends-on = ["remove-file"] }
