jobs:
  stage_0_job_0:
    name: robotiq-description mocap4r2-control-msgs robotiq-controllers mocap4r2-control
    runs-on: macos-15-intel
    strategy:
      fail-fast: false
    needs: []
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Build ros-humble-robotiq-description ros-humble-mocap4r2-control-msgs
        ros-humble-robotiq-controllers ros-humble-mocap4r2-control
      env:
        ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        CURRENT_RECIPES: ros-humble-robotiq-description ros-humble-mocap4r2-control-msgs
          ros-humble-robotiq-controllers ros-humble-mocap4r2-control
        BUILD_TARGET: osx-64
      run: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/build_unix.sh --target $BUILD_TARGET
name: build_osx64
on:
  push:
    branches:
    - buildbranch_osx
